---
all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3.10
    registry_url: registry-proxy:443
    registry_username: testuser
    registry_password: testpassword
    ansible_user: ansible
    ansible_password: pass
  children:
    webservers:
      hosts:
        ansible-ci-cd-app-3:
        ansible-ci-cd-app-4:
  hosts:
    ansible-ci-cd-app-1:
      ansible_host: 172.20.0.5
    ansible-ci-cd-app-2:
      ansible_host: 172.20.0.4
    ansible-ci-cd-app-3:
      ansible_host: 172.20.0.3
    ansible-ci-cd-app-4:
      ansible_host: 172.20.0.6
